generate-stackapps \
    --about "Template repository for UserScripters projects." \
    --chrome "100.0.4896.127" \
    --excerpt "This is a placeholder repository and should be customized upon forking" \
    --install "https://github.com/userscripters/template/raw/master/dist/modern/index.user.js" \
    --minified "https://github.com/userscripters/template/raw/master/dist/modern/index.min.user.js" \
    --language "TypeScript" \
    --org-name "UserScripters" \
    --org-url "https://github.com/userscripters" \
    --room "https://chat.stackoverflow.com/rooms/214345" \
    --screenshot-alt "a post being highlighted and de-highlighted after a delay" \
    --screenshot-url "https://i.stack.imgur.com/55TGz.gif" \
    --tag "script"
